name: Deploy Medusa Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Update and Install Dependencies
      run: |
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Update and install necessary packages
          sudo apt-get update -y
          sudo apt-get upgrade -y
          
          # Install Node.js 18.x
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs
          
          # Install PostgreSQL
          sudo apt install -y postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl enable postgresql

          # Create PostgreSQL database and user
          sudo -u postgres psql -c "CREATE USER medusabackend WITH PASSWORD 'medusa123' CREATEDB;"
          sudo -u postgres psql -c "CREATE DATABASE medusabackend OWNER medusabackend;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE medusabackend TO medusabackend;"

          # Install Redis
          sudo apt install -y redis-server
          sudo systemctl enable redis-server
          sudo systemctl start redis-server

          # Clone the Medusa app repository
          if [ -d "./my-app-store" ]; then
            sudo rm -rf ./my-app-store
          fi
          git clone https://github.com/palemanudeep/TASK-3.git ./my-app-store
          cd ./my-app-store

          # Set up .env file
          touch .env
          echo "DATABASE_URL=postgres://medusabackend:medusa123@localhost:5432/medusabackend" > .env
          echo "REDIS_URL=redis://localhost:6379" >> .env

          # Install Medusa dependencies
          sudo npm install -g @medusajs/medusa-cli
          npm install
          npm install cross-env --save-dev

          # Run database migrations
          npx medusa migrations run

          # Create Medusa admin user
          npx medusa user -e anudeep@gmail.com -p anudeep123

          # Start the Medusa application in the background
          nohup sudo npm run start &> medusa.log &

          echo "Medusa deployment initiated."

        EOF
